### PR TITLE
Pull request for capstone review

### PR DESCRIPTION
**Pull request by leonmezu1**
# Project specifications:

In this project, I intend to showcase my dev skills building from scratch a social network app.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Errors when testing

Hello, 
When reviewing your captsone project, I got this error when running `rspec`

```ruby
Failures:

  1) User Sign up successfully sign up
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdae82f18>
     # ./spec/features/users_feature_spec.rb:27:in `block (3 levels) in <main>'

  2) User Sign up successfully home
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdbf0dab8>
     # ./spec/features/users_feature_spec.rb:32:in `block (3 levels) in <main>'

  3) User Sign up successfully route to profile
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdbf21540>
     # ./spec/features/users_feature_spec.rb:38:in `block (3 levels) in <main>'

  4) User Sign up successfully route to future feature
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdc24d340>
     # ./spec/features/users_feature_spec.rb:45:in `block (3 levels) in <main>'

  5) User Sign up successfully log out
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdaa9d330>
     # ./spec/features/users_feature_spec.rb:52:in `block (3 levels) in <main>'

  6) User Sign up successfully log in
     Failure/Error: sign_up
     
     NameError:
       undefined local variable or method `sign_up' for #<RSpec::ExampleGroups::User::SignUp:0x0000559fdb4c7c98>
     # ./spec/features/users_feature_spec.rb:59:in `block (3 levels) in <main>'

Deprecation Warnings:

Requiring `rspec/autorun` when running RSpec via the `rspec` command is deprecated. Called from /home/maelfosso/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 10.68 seconds (files took 4.23 seconds to load)
65 examples, 6 failures

Failed examples:

rspec ./spec/features/users_feature_spec.rb:26 # User Sign up successfully sign up
rspec ./spec/features/users_feature_spec.rb:31 # User Sign up successfully home
rspec ./spec/features/users_feature_spec.rb:37 # User Sign up successfully route to profile
rspec ./spec/features/users_feature_spec.rb:44 # User Sign up successfully route to future feature
rspec ./spec/features/users_feature_spec.rb:51 # User Sign up successfully log out
rspec ./spec/features/users_feature_spec.rb:58 # User Sign up successfully log in
```

Thanks, 
Mael FOSSO

**Comment by leonmezu1** [comment]
Tests are now fixed.

**Comment by leonmezu1** [comment]
# Regarding Nice to have section:

Nice to have

Isaac Verrall Browne:  ~ Not intrusive avatar-cover update implemented
Fatima Ahmed Muhsin Mahmoud: ~Main comments remaining are cop disable statements
Mael Fosso Nguetchuessi: ~ I'll try to implement this and new features along this week :smile: 

Thank you very much!

**Comment by leonmezu1** [comment]
Capstone approved!

**Pull request merged**
